kind: Deployment
apiVersion: apps/v1
metadata:
  name: lista-compras
  namespace: azure-vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lista-compras
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lista-compras
    spec:
      containers:
        - name: lista-compras
          image: docker.io/rnascimento86/lc:v1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: DB_HOST
              value: lista-compras-mysql-service
            - name: DB_PORT
              value: '3306'
            - name: DB_DATABASE
              value: 'lista_compras'
            - name: DB_USERNAME
              value: 'root'
            - name: DB_PASSWORD
              value: ''
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        beta.kubernetes.io/os: linux
status: {}
