kind: Deployment
apiVersion: apps/v1
metadata:
  name: lista-compras-mysql
  namespace: azure-vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lista-compras-mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lista-compras-mysql
    spec:
      containers:
        - name: lista-compras-mysql
          image: docker.io/mysql:8.0.30
          ports:
            - name: mysql-port
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_ROOT_PASSWORD
              value: ""
          resources:
            limits:
              cpu: "1"
              memory: "1Gi" 
            requests:
              cpu: "100m"
              memory: "512Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        beta.kubernetes.io/os: linux
status: {}
